# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Node = channel.unary_unary(
                '/Calculator/Node',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )
        self.Node_GPU = channel.unary_unary(
                '/Calculator/Node_GPU',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Node(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Node_GPU(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Node': grpc.unary_unary_rpc_method_handler(
                    servicer.Node,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
            'Node_GPU': grpc.unary_unary_rpc_method_handler(
                    servicer.Node_GPU,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Node(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/Node',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Node_GPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/Node_GPU',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
